config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }

  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <div class="form-inputs">
    <%= f.input :name, input_html: { placeholder: "Spaggetti Factory"} %>
    <%= f.input :address %>
    <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES, include_blank: "Select a category" %>
    <%= f.input :phone_number, input_html: { placeholder: "000-123-4567"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Editting Restaurant</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to "Show", restaurant_path %>|<%= link_to "Back", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<h1>All our restaurants</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="info">Name</th>
      <th class="warning">Adress</th>
      <th class="danger">Category</th>
      <th class="active">Phone Number</th>
      <th class="success">Other options</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.category %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= link_to "Show", restaurant_path(restaurant) %>|<%= link_to "Edit", edit_restaurant_path(restaurant) %>|<%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4><%= link_to "New restaurant", new_restaurant_path %></h4>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>

  <%= render "form", restaurant: @restaurant %>
  <%= link_to "Back", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2><%= @restaurant.name %></h2>
  <ul class="list-group">
    <li class="list-group-item"><%= @restaurant.address %></li>
    <li class="list-group-item"><%= @restaurant.category %></li>
    <li class="list-group-item"><%= @restaurant.phone_number %></li>
  </ul>

  <h4>Our reviews</h4>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item"><%= review.content %></li>
      <li class="list-group-item">Rating: <%= review.rating %></li>
    <% end %>
  </ul>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %> |
  <%= link_to "Create a review", new_restaurant_review_path(@restaurant) %>

</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>